interface HelpProps {
    onClose: () => void
}

interface Section {
    title: string
    rows: { term: string; def: string }[]
}

const SECTIONS: Section[] = [
    {
        title: 'Materials',
        rows: [
            {
                term: 'Si — Silicon',
                def: 'The workhorse of modern electronics. Diamond cubic lattice, band gap ~1.1 eV at room temperature. All other materials are benchmarked against it.',
            },
            {
                term: 'Ge — Germanium',
                def: "Narrower gap (0.66 eV) and higher electron mobility than Si, but pays for it thermally: intrinsic carriers overwhelm dopants above ~400 K at typical concentrations, destroying the device's designed behaviour.",
            },
            {
                term: 'GaN — Gallium Nitride',
                def: 'Wide-bandgap material (3.4 eV). Intrinsic carrier concentration is negligibly small even at 600 K, so it stays controlled where Si and Ge give up. The basis of high-voltage power transistors, RF amplifiers, and LEDs.',
            },
            {
                term: 'Graphene',
                def: 'A single layer of carbon atoms. Zero band gap at the Dirac point — not a conventional semiconductor. Strain up to ±2% does not open a gap. Conductivity has a universal minimum of 4e²/h that is nearly temperature-independent.',
            },
        ],
    },
    {
        title: 'Doping',
        rows: [
            {
                term: 'n-type',
                def: 'Donor impurities substituted into the lattice donate free electrons as majority carriers. Dopant species: P in Si, As in Ge, Si in GaN, N in graphene.',
            },
            {
                term: 'p-type',
                def: 'Acceptor impurities capture electrons, leaving mobile holes as majority carriers. Dopant species: B in Si and Ge, Mg in GaN, B in graphene.',
            },
            {
                term: 'Intrinsic crossover',
                def: 'When temperature is high enough, thermally-generated carrier pairs (nᵢ) outnumber the intentional dopants. The material loses its engineered character and becomes effectively intrinsic. This happens in Ge around 400–500 K, but GaN stays doped up to and well beyond 600 K.',
            },
        ],
    },
    {
        title: 'Controls',
        rows: [
            {
                term: 'Temperature (100–700 K)',
                def: 'Raises phonon density, increasing scattering and lowering mobility. Also increases nᵢ exponentially, driving the intrinsic crossover. The Varshni equation describes the slight shrinkage of the band gap with temperature.',
            },
            {
                term: 'Doping (10¹⁴–10²⁰ cm⁻³)',
                def: 'Higher doping raises majority carrier count linearly, but ionised impurity scattering degrades mobility — captured by the Caughey–Thomas model. There is a trade-off: more carriers, slower carriers.',
            },
            {
                term: 'Strain (±2%)',
                def: "Deformation-potential theory: tensile strain (positive) distorts the band structure and lowers the band gap. In Si, +1% uniaxial tensile strain boosts electron mobility by ~17% — the mechanism behind Intel's strained-channel transistors at the 90 nm node. Poisson contraction shrinks the transverse axes as the crystal is pulled.",
            },
        ],
    },
    {
        title: 'Output values',
        rows: [
            {
                term: 'Eɡ — Band gap',
                def: 'Energy separation between the valence and conduction bands, in eV. Electrons need at least this energy to conduct. Zero for graphene; decreases with rising temperature and tensile strain for conventional semiconductors.',
            },
            {
                term: 'n, p — Carrier concentrations',
                def: 'Density of free electrons (n) and holes (p) in cm⁻³, or sheet density in cm⁻² for graphene. The product n·p = nᵢ² always holds in equilibrium (mass-action law). In heavily doped n-type material n ≈ N_D; at high temperature nᵢ takes over.',
            },
            {
                term: 'nᵢ — Intrinsic concentration',
                def: 'Carriers generated by thermal excitation alone, independent of doping. Sets the lower bound on conductivity and the temperature at which a device goes intrinsic.',
            },
            {
                term: 'μₙ, μₚ — Mobilities',
                def: 'Drift velocity per unit electric field, in cm²/V·s. High mobility = fast device. Degraded by phonon scattering (rises with T) and impurity scattering (rises with N). Tensile strain enhances μₙ in Si via band warping.',
            },
            {
                term: 'σ — Conductivity',
                def: 'σ = q(nμₙ + pμₚ), in S/cm for bulk or S/□ (siemens per square) for graphene sheet conductance. Combine the carrier density story and the mobility story: both matter.',
            },
            {
                term: 'ρ — Resistivity',
                def: 'Reciprocal of conductivity, in Ω·cm or Ω/□. This is the number measured with a four-point probe. Intrinsic Si at room temperature: ~2300 Ω·cm. Heavily doped: < 0.001 Ω·cm.',
            },
            {
                term: 'a — Lattice constant',
                def: 'Distance between equivalent lattice planes, in ångströms. Scales as a₀(1+ε) along the strain axis, with Poisson contraction on the transverse axes. Drives the 3D view: every atom position is derived from this.',
            },
        ],
    },
]

export function Help({ onClose }: HelpProps) {
    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center p-xl"
            style={{ backgroundColor: 'rgba(0,0,0,0.75)' }}
            onClick={onClose}
        >
            <div
                className="relative bg-bg-b border border-bg-d rounded-lg w-full max-w-4xl max-h-[80vh] overflow-y-auto"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="sticky top-0 bg-bg-b border-b border-bg-d flex items-center justify-between px-xl py-md z-10">
                    <span className="text-fg-a font-medium">How this works</span>
                    <button
                        onClick={onClose}
                        className="text-fg-b hover:text-fg-a transition-colors text-lg leading-none cursor-pointer"
                    >
                        ✕
                    </button>
                </div>

                {/* Intro */}
                <div className="px-xl pt-lg pb-md">
                    <p className="text-sm text-fg-b leading-relaxed">
                        A live semiconductor physics explorer. Adjust the sliders to see how temperature,
                        doping, and strain change the electrical properties of four key materials —
                        every number updates in real time from the underlying physics equations.
                    </p>
                </div>

                {/* Sections */}
                <div className="px-xl pb-xl flex flex-col gap-xl">
                    {SECTIONS.map(section => (
                        <div key={section.title} className="flex flex-col gap-md">
                            <h2 className="text-xs text-fg-b uppercase tracking-wider border-b border-bg-d pb-sm">
                                {section.title}
                            </h2>
                            <dl className="flex flex-col gap-md">
                                {section.rows.map(({ term, def }) => (
                                    <div key={term}>
                                        <dt className="text-sm text-accent font-medium mb-xs">{term}</dt>
                                        <dd className="text-sm text-fg-b leading-relaxed">{def}</dd>
                                    </div>
                                ))}
                            </dl>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}
